export const ERROR_CODE = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  NOT_FOUND: 'NOT_FOUND',

  ALREADY_EXISTS: 'ALREADY_EXISTS',

  USER_NOT_VERIFIED: 'USER_NOT_VERIFIED',
  USER_ALREADY_VERIFIED: 'USER_ALREADY_VERIFIED',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  SAME_PASSWORD: 'SAME_PASSWORD',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_CODE: 'INVALID_CODE',
  ROLE_FORBIDDEN: 'ROLE_FORBIDDEN',

  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',

  CART_IS_EMPTY: 'CART_IS_EMPTY',
  CART_CREATION_FAILED: 'CART_CREATION_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
